<script setup lang="ts">
import { onMounted, ref, shallowRef } from 'vue';
import { errorText, numberText, type ManagementClient } from '../api.js';
import type { ServerInfo, Stats, Usage } from '../server-types.js';
import { useRequest } from '../useRequest.js';
import ConfirmDialog from '../components/ConfirmDialog.vue';
import RequestState from '../components/RequestState.vue';
import UsageChart from '../components/UsageChart.vue';
const props = defineProps<{ client: ManagementClient; info: ServerInfo }>();
const emit = defineEmits<{ sessionLost: []; restart: []; refreshInfo: [] }>();
const { busy, writing, error, run, cancel } = useRequest(props.client, () => emit('sessionLost'));
const stats = shallowRef<Stats>(), usage = shallowRef<Usage>(), usageError = ref(''), confirmRestart = ref(false);
async function load() {
  stats.value = undefined; usage.value = undefined; usageError.value = '';
  await run(async (signal) => {
    const requests = [props.client.request<Stats>('/stats', undefined, true, undefined, signal), ...(props.info.management?.capabilities?.aiUsage ? [props.client.request<Usage>('/ai/usage?days=7', undefined, true, undefined, signal)] : [])];
    return Promise.allSettled(requests);
  }, (results) => { const summary = results[0]; if (summary?.status === 'fulfilled') stats.value = summary.value as Stats; else if (summary?.status === 'rejected') error.value = errorText(summary.reason); const trend = results[1]; if (trend?.status === 'fulfilled') usage.value = trend.value as Usage; else if (trend?.status === 'rejected') usageError.value = errorText(trend.reason); if (!props.client.session) emit('sessionLost'); });
}
async function restart() { if (props.info.management?.capabilities?.restart !== true) return; await run(() => props.client.request('/server/restart', {}), () => emit('restart'), true); }
onMounted(load);
</script>
<template><div class="panel-toolbar"><h3>运行概览</h3><button type="button" :disabled="busy" @click="$emit('refreshInfo'); load()">刷新</button></div><RequestState :busy="busy" :writing="writing" :error="confirmRestart ? '' : error" @cancel="cancel" /><div v-if="stats" class="metric-grid"><div class="metric"><span>用户总数</span><strong>{{ numberText(stats.users.total) }}</strong><small>近 7 天新增 {{ numberText(stats.users.newLast7Days) }}</small></div><div class="metric"><span>启用 / 停用用户</span><strong class="compact-value">{{ numberText(stats.users.active) }} / {{ numberText(stats.users.disabled) }}</strong></div><div class="metric"><span>可用邀请码</span><strong>{{ numberText(stats.invites?.available) }}</strong><small>共 {{ numberText(stats.invites?.total) }} 个</small></div><div class="metric"><span>待处理反馈</span><strong>{{ numberText(stats.feedback.open) }}</strong><small>处理中 {{ numberText(stats.feedback.inProgress) }} · 已解决 {{ numberText(stats.feedback.resolved) }}</small></div></div>
<div class="overview-columns"><section class="surface"><h3>服务信息</h3><dl class="detail-list"><dt>Server 版本</dt><dd>{{ info.version ?? '—' }}</dd><dt>代码提交</dt><dd class="mono">{{ info.commit ?? '—' }}</dd><dt>数据库</dt><dd>{{ info.database?.connected === true || info.database?.status === 'connected' ? '已连接' : info.database?.connected === false || info.database?.status === 'down' ? '未连接' : '—' }}</dd></dl><button type="button" class="danger" :disabled="busy || !info.management?.capabilities?.restart" @click="confirmRestart = true; error = ''">重启 Server</button><p v-if="!info.management?.capabilities?.restart" class="field-hint">该节点未启用远程重启。</p></section><section v-if="stats" class="surface"><h3>近 7 天活动</h3><dl class="detail-list"><dt>上报练习</dt><dd>{{ numberText(stats.activity.attemptsLast7Days) }} 次</dd><dt>上报用户</dt><dd>{{ numberText(stats.activity.reportedUsersLast7Days) }} 个</dd><dt>AI 请求 / 失败</dt><dd>{{ numberText(stats.ai.callsLast7Days) }} / {{ numberText(stats.ai.failedLast7Days) }} 次</dd><dt>共享池费用</dt><dd>{{ numberText(stats.ai.poolCostCentsLast7Days) }} 美分</dd></dl><p class="field-hint">练习统计仅包括 Server 已收到的已登录用户记录。</p></section></div>
<div v-if="stats?.invites" class="count-grid surface"><div v-for="(label, key) in { once: '一次性邀请码', permanent: '长期邀请码', disabled: '已撤销', expired: '已过期', used: '已使用' }" :key="key"><span>{{ label }}</span><strong>{{ numberText(stats.invites[key]) }}</strong></div></div><p v-if="usageError" class="message error" role="alert">AI 趋势：{{ usageError }}</p><section v-if="usage" class="surface"><UsageChart :days="usage.byDay" /><details v-if="usage.byDay.length"><summary>查看每日数值</summary><div class="table-wrap" tabindex="0" role="region" aria-label="近 7 天 AI 请求趋势数值"><table><caption class="sr-only">近 7 天 AI 请求</caption><thead><tr><th scope="col">日期（UTC）</th><th scope="col">请求</th><th scope="col">失败</th><th scope="col">共享池费用（美分）</th></tr></thead><tbody><tr v-for="day in usage.byDay" :key="day.date"><th scope="row">{{ day.date }}</th><td>{{ numberText(day.calls) }}</td><td>{{ numberText(day.failed) }}</td><td>{{ numberText(day.poolCostCents) }}</td></tr></tbody></table></div></details><p v-else class="empty-state">近 7 天没有 AI 调用。</p></section><ConfirmDialog v-if="confirmRestart" title="重启 Server" description="登录、同步和 AI 服务会短暂中断，恢复后需重新登录管理控制台。" confirm-label="确认重启" danger :busy="writing" :error="error" @confirm="restart" @close="confirmRestart = false; error = ''" /></template>
