export const IPC = {
  storageGet: 'qed2:storage:get',
  storageSet: 'qed2:storage:set',
  storageDelete: 'qed2:storage:delete',
  storageKeys: 'qed2:storage:keys',
  storageClear: 'qed2:storage:clear',
  storageChange: 'qed2:storage:change',
  coreGetEndpoint: 'qed2:core:get-endpoint',
  coreConfigure: 'qed2:core:configure',
  coreGetStatus: 'qed2:core:get-status',
  coreRecover: 'qed2:core:recover',
  coreStatus: 'qed2:core:status',
  updateCheck: 'qed2:update:check',
  updateGetState: 'qed2:update:get-state',
  updateApply: 'qed2:update:apply',
  updateRelaunch: 'qed2:update:relaunch',
  updateState: 'qed2:update:state',
  networkGet: 'qed2:network:get',
  networkChange: 'qed2:network:change',
  shellCommand: 'qed2:shell:command',
  shellOpenWindow: 'qed2:shell:open-window',
} as const;
