import { describe, expect, it } from 'vitest';
import {
  EMPTY_ARCHIVE_CHECKSUM,
  archiveChecksum,
  canonicalArchiveString,
  stableStringify,
} from '../src/sync/index.js';
import { normNum } from '../src/model/archive.js';
import type { ArchiveContent } from '../src/model/archive.js';
import vectors from './fixtures/checksum-vectors.json';

/**
 * Vectors are generated by the VERBATIM reference implementation from
 * QED2-checksum-spec.md §7 (node:crypto oracle, scratch script) — our
 * production implementation (@noble/hashes) must match string-for-string
 * and hash-for-hash. Final cross-validation against the live upgraded
 * server happens in e2e-live.spec.ts.
 */
interface Vector {
  name: string;
  content: ArchiveContent;
  checksum: string;
  canonical: string;
}

describe('checksum vectors (spec §7 reference implementation oracle)', () => {
  for (const vector of vectors as Vector[]) {
    it(`matches canonical string and checksum for "${vector.name}"`, () => {
      expect(canonicalArchiveString(vector.content)).toBe(vector.canonical);
      expect(archiveChecksum(vector.content)).toBe(vector.checksum);
    });
  }

  it('EMPTY_ARCHIVE_CHECKSUM equals the spec §6 fixed value', () => {
    const empty = (vectors as Vector[]).find((v) => v.name === 'empty');
    expect(empty).toBeDefined();
    expect(EMPTY_ARCHIVE_CHECKSUM).toBe(empty!.checksum);
    // Unchanged from the pre-grading era: {"perCompetency":[],"perPart":[]}
    expect(EMPTY_ARCHIVE_CHECKSUM).toBe(
      '389e57af4fe5f0cea96241a5916185940cd3d1b7e66a5983e13f6c2c30b857be',
    );
  });

  it('sorts deliberately-unsorted input arrays (spec §2 step 2)', () => {
    const v = (vectors as Vector[]).find((x) => x.name === 'full-mixture')!;
    // Input order: z-… before a-…; "WS 3.1" before "AG 1.1".
    expect(v.content.perPart[0]!.partId > v.content.perPart[1]!.partId).toBe(true);
    const canonical = canonicalArchiveString(v.content);
    expect(canonical.indexOf('a-2019-ht-t1-02-a')).toBeLessThan(canonical.indexOf('z-2023-ht-t1-09-a'));
    expect(canonical.indexOf('AG 1.1')).toBeLessThan(canonical.indexOf('WS 3.1'));
    // order-independence: shuffled input → same checksum
    const shuffled: ArchiveContent = {
      perPart: [...v.content.perPart].reverse(),
      perCompetency: [...v.content.perCompetency].reverse(),
    };
    expect(archiveChecksum(shuffled)).toBe(v.checksum);
  });
});

describe('field optionality semantics (spec §5.3)', () => {
  const base: ArchiveContent = {
    perPart: [
      {
        partId: 'p1',
        grading: null,
        starred: false,
        fsrs: {
          due: '2026-07-04T00:00:00.000Z',
          stability: 1,
          difficulty: 5,
          reps: 1,
          lapses: 0,
          lastReview: null,
        },
        updatedAt: '2026-07-03T08:30:00.000Z',
      },
    ],
    perCompetency: [],
  };

  it('lastReview null is RETAINED as null; lastResult absent is OMITTED', () => {
    const canonical = canonicalArchiveString(base);
    expect(canonical).toContain('"lastReview":null');
    expect(canonical).not.toContain('lastResult');
  });

  it('grading unset serializes as null (key retained); starred always present', () => {
    const canonical = canonicalArchiveString(base);
    expect(canonical).toContain('"grading":null');
    expect(canonical).toContain('"starred":false');
  });

  it('loose legacy input (missing grading/starred/lastReview keys) canonicalizes identically', () => {
    const legacy = {
      perPart: [
        {
          partId: 'p1',
          fsrs: { due: '2026-07-04T00:00:00.000Z', stability: 1, difficulty: 5, reps: 1, lapses: 0 },
          updatedAt: '2026-07-03T08:30:00.000Z',
        },
      ],
      perCompetency: [],
    } as unknown as ArchiveContent;
    expect(canonicalArchiveString(legacy)).toBe(canonicalArchiveString(base));
    expect(archiveChecksum(legacy)).toBe(archiveChecksum(base));
  });

  it('key order inside a part entry follows code-point sorting (spec §3)', () => {
    const withResult: ArchiveContent = {
      perPart: [
        {
          ...base.perPart[0]!,
          grading: 'good',
          lastResult: { correct: true, awardedPoints: 1, gradedAt: '2026-07-03T08:30:00.000Z' },
        },
      ],
      perCompetency: [],
    };
    const canonical = canonicalArchiveString(withResult);
    const idx = (k: string) => canonical.indexOf(`"${k}"`);
    // fsrs < grading < lastResult < partId < starred < updatedAt
    expect(idx('fsrs')).toBeLessThan(idx('grading'));
    expect(idx('grading')).toBeLessThan(idx('lastResult'));
    expect(idx('lastResult')).toBeLessThan(idx('partId'));
    expect(idx('partId')).toBeLessThan(idx('starred'));
    expect(idx('starred')).toBeLessThan(idx('updatedAt'));
    // fsrs inner: difficulty, due, lapses, lastReview, reps, stability
    expect(idx('difficulty')).toBeLessThan(idx('due'));
    expect(idx('due')).toBeLessThan(idx('lapses'));
    expect(idx('lapses')).toBeLessThan(idx('lastReview'));
    expect(idx('lastReview')).toBeLessThan(idx('reps'));
    expect(idx('reps')).toBeLessThan(idx('stability'));
  });

  it('stableStringify drops undefined-valued keys but keeps null', () => {
    expect(stableStringify({ a: undefined, b: 1 })).toBe('{"b":1}');
    expect(stableStringify({ a: null })).toBe('{"a":null}');
  });
});

describe('float normalization (spec §5.1)', () => {
  it('normNum: integers pass through, floats round to 6 decimals half up', () => {
    expect(normNum(5)).toBe(5);
    expect(normNum(3.2)).toBe(3.2);
    expect(normNum(1.0000005)).toBe(1.000001);
    expect(normNum(0.1234564999)).toBe(0.123456);
    expect(normNum(0.3333333333333333)).toBe(0.333333);
    expect(() => normNum(Number.NaN)).toThrow();
    expect(() => normNum(Number.POSITIVE_INFINITY)).toThrow();
  });

  it('float noise below 1e-6 does not change the checksum', () => {
    const mk = (stability: number): ArchiveContent => ({
      perPart: [
        {
          partId: 'p1',
          grading: null,
          starred: false,
          fsrs: { due: '2026-01-01T00:00:00.000Z', stability, difficulty: 5, reps: 1, lapses: 0, lastReview: null },
          updatedAt: '2026-01-01T00:00:00.000Z',
        },
      ],
      perCompetency: [],
    });
    expect(archiveChecksum(mk(3.2))).toBe(archiveChecksum(mk(3.2000001)));
    expect(archiveChecksum(mk(3.2))).not.toBe(archiveChecksum(mk(3.21)));
  });
});

describe('field sensitivity (spec §8)', () => {
  const mk = (over: Partial<{ grading: 'good' | null; starred: boolean; stability: number }>): ArchiveContent => ({
    perPart: [
      {
        partId: 'p1',
        grading: over.grading ?? null,
        starred: over.starred ?? false,
        fsrs: {
          due: '2026-01-01T00:00:00.000Z',
          stability: over.stability ?? 1,
          difficulty: 5,
          reps: 1,
          lapses: 0,
          lastReview: null,
        },
        updatedAt: '2026-01-01T00:00:00.000Z',
      },
    ],
    perCompetency: [],
  });

  it('changing grading / starred / fsrs values changes the checksum', () => {
    const baseline = archiveChecksum(mk({}));
    expect(archiveChecksum(mk({ grading: 'good' }))).not.toBe(baseline);
    expect(archiveChecksum(mk({ starred: true }))).not.toBe(baseline);
    expect(archiveChecksum(mk({ stability: 2 }))).not.toBe(baseline);
  });
});

describe('timestamp normalization (spec §5.4)', () => {
  it('normalizes non-canonical timezone offsets to ISO UTC ms precision', () => {
    const offsetContent: ArchiveContent = {
      perPart: [
        {
          partId: 'p1',
          grading: null,
          starred: false,
          fsrs: {
            due: '2026-01-01T00:00:00+02:00',
            stability: 1,
            difficulty: 5,
            reps: 1,
            lapses: 0,
            lastReview: '2025-12-31T23:00:00+01:00',
          },
          updatedAt: '2026-01-01T02:00:00+02:00',
        },
      ],
      perCompetency: [{ code: 'AG 1.1', mastery: 0.5, updatedAt: '2026-01-01T00:00:00+02:00' }],
    };
    const canonical = canonicalArchiveString(offsetContent);
    expect(canonical).toContain('2025-12-31T22:00:00.000Z');
    expect(canonical).not.toContain('+02:00');
  });
});

describe('unicode handling (spec §5.5)', () => {
  it('sorts unicode object keys by code point and encodes like JSON.stringify', () => {
    const value = { 'ü': 1, 'a': 2, 'ß': 3, 'Z': 4 };
    // Code point order: 'Z' (0x5A) < 'a' (0x61) < 'ß' (0xDF) < 'ü' (0xFC).
    expect(stableStringify(value)).toBe('{"Z":4,"a":2,"ß":3,"ü":1}');
    expect(stableStringify('ä✓')).toBe(JSON.stringify('ä✓'));
  });
});
