/**
 * The changelog format, in one place.
 *
 * Two scripts share it and must agree exactly:
 *   scripts/fold-changelog.mjs        writes CHANGELOG.md   (release time, local)
 *   packages/web/scripts/build-changelog.mjs  reads it      (build time)
 *
 * Format — deliberately boring, so a human can edit it and a regex can read it:
 *
 *   ## 1.9.6 — 2026-07-27
 *
 *   ### layout update!
 *
 *   the bar under a checked answer stopped stepping on itself. …
 *
 * The heading carries the two machine fields (version, date) and nothing else.
 * Everything below it, up to the next `## `, is the note body verbatim.
 */

/** `## <version> — <date>`; the dash may be em or ascii, spacing is loose. */
const HEADING = /^##\s+(\S+)\s*[—–-]\s*(\d{4}-\d{2}-\d{2})\s*$/;

/** Releases are dated where QED2 is operated, not at UTC midnight. */
export const RELEASE_TIME_ZONE = 'Asia/Shanghai';

/** Return the calendar date for a release instant in the canonical timezone. */
export function releaseDate(date = new Date()) {
  if (!(date instanceof Date) || Number.isNaN(date.getTime())) {
    throw new TypeError('releaseDate requires a valid Date');
  }

  const parts = new Intl.DateTimeFormat('en-US', {
    timeZone: RELEASE_TIME_ZONE,
    year: 'numeric',
    month: '2-digit',
    day: '2-digit',
  }).formatToParts(date);
  const value = (type) => parts.find((part) => part.type === type)?.value;
  const year = value('year');
  const month = value('month');
  const day = value('day');
  if (!year || !month || !day) throw new Error('Could not format release date');
  return `${year}-${month}-${day}`;
}

export const CHANGELOG_PREAMBLE = `# Changelog

<!--
  Released notes, newest first. Generated by scripts/fold-changelog.mjs when a
  commit bumps the version in the root package.json — do not add a section by
  hand. The next release's notes belong in
  packages/web/public/changelogs/latest.md.

  The app ships exactly this text (packages/web/scripts/build-changelog.mjs
  compiles it into dist/changelogs/index.json), so anything written here is
  read by users.
-->
`;

/**
 * Parse a CHANGELOG.md into entries, newest first (i.e. file order).
 *
 * Order is the contract, not an accident: the client picks "everything you
 * have not seen" by walking down from the top, which needs no semver
 * comparison and therefore cannot be confused by 1.9.7 vs 1.10.0.
 */
export function parseChangelog(text) {
  const entries = [];
  let current = null;
  for (const line of text.split('\n')) {
    const m = HEADING.exec(line);
    if (m) {
      if (current) entries.push(finish(current));
      current = { version: m[1], date: m[2], lines: [] };
    } else if (current) {
      current.lines.push(line);
    }
  }
  if (current) entries.push(finish(current));
  return entries;
}

function finish(section) {
  return { version: section.version, date: section.date, body: section.lines.join('\n').trim() };
}

/**
 * Turn a draft into the body of a released section.
 *
 * A leading `# …` is demoted to `###` and stripped of any version echo, so the
 * old habit of typing `# QED2 1.9.6 - layout update!` still yields a usable
 * `### layout update!` — the version is the section heading's job now, and
 * writing it twice is exactly the drift this refactor removes. Nothing is
 * dropped except the version itself.
 */
export function normalizeDraft(draft, version) {
  const lines = draft.trim().split('\n');
  const first = lines[0] ?? '';
  const h1 = /^#\s+(.*)$/.exec(first);
  if (!h1) return lines.join('\n').trim();

  let title = h1[1].trim();
  // "QED2 1.9.6 - layout update!" → "layout update!"; "QED2 1.9.7" → ""
  title = title
    .replace(/^QED2\s*/i, '')
    .replace(/^v?\d+(\.\d+)*(-[\w.]+)?\s*/, '')
    .replace(/^[—–\-·:]\s*/, '')
    .trim();
  // A title that was only the version leaves nothing worth keeping.
  const rest = lines.slice(1).join('\n').trim();
  return title === '' ? rest : `### ${title}\n\n${rest}`.trim();
}

export function formatSection(version, date, body) {
  return `## ${version} — ${date}\n\n${body.trim()}\n`;
}

/**
 * Prepend a section, keeping the preamble on top.
 *
 * Idempotence is the point: re-running at the same version is a no-op, so the
 * pre-commit hook can run on every commit without a guard of its own.
 */
export function prependSection(changelog, version, date, body) {
  const existing = parseChangelog(changelog);
  if (existing.some((e) => e.version === version)) return null;

  const firstHeading = changelog.search(/^## /m);
  const preamble = firstHeading === -1 ? changelog.trimEnd() : changelog.slice(0, firstHeading).trimEnd();
  const rest = firstHeading === -1 ? '' : changelog.slice(firstHeading);
  const head = preamble === '' ? CHANGELOG_PREAMBLE.trimEnd() : preamble;
  return `${head}\n\n${formatSection(version, date, body)}${rest === '' ? '' : `\n${rest}`}`;
}

/** A prerelease (2.0.0-beta.10) is not a release and never cuts a section. */
export function isPrerelease(version) {
  return version.includes('-');
}
